- id: '1703910468139'
  alias: Dim lights when TV LED on
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: d15b188afbaf9ee89d930c8562b90e43
    entity_id: 2b8e3356b2c40c937a32e0591a002acc
    domain: light
  condition: []
  action:
  - device_id: 638ff6dbd16db764b99b0b1bc72a8a31
    domain: light
    entity_id: a37b21ddc27f77fa2c928543f0a7664a
    type: brightness_decrease
  mode: single
- id: '1704999401076'
  alias: Flash lights
  description: ''
  trigger: []
  condition: []
  action:
  - service: scene.create
    metadata: {}
    data:
      scene_id: lights_current
      snapshot_entities:
      - light.tv_led
      - light.le_rgbcwbr30
      - light.le_rgbcwbr30_2
      - light.kitchen_bulb_3
      - light.le_rgbcwbr30_3
      - light.office_light
      - light.bedroom_light
      - light.living_room_light
      - light.dining_room_light
      - switch.kitchen_lights_switch_1
      - switch.under_cabinet_lights_switch_1
      - switch.dinette_light_switch_1
  - repeat:
      count: 3
      sequence:
      - service: script.turn_on_house
        metadata: {}
        data: {}
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
      - service: script.turn_off_house
        metadata: {}
        data: {}
  - service: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.lights_current
  - service: scene.delete
    metadata: {}
    data: {}
    target:
      entity_id: scene.lights_current
  mode: single
- id: '1705119000216'
  alias: Cat water filter low
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: 249f4195abe2c4e17b946d59cda4a8c0
    entity_id: 5309c742c4d5a7d09930feb84d4bd64b
    domain: sensor
    below: 30
  condition: []
  action:
  - service: shopping_list.add_item
    metadata: {}
    data:
      name: cat water filter
  - service: notify.persistent_notification
    metadata: {}
    data:
      message: The cat filter is low!
      title: Clean me..
  mode: single
- id: '1705119040659'
  alias: Cat water is low
  description: ''
  trigger:
  - type: problem
    platform: device
    device_id: 249f4195abe2c4e17b946d59cda4a8c0
    entity_id: af9f996438fb812d4cf832219053d343
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - service: notify.persistent_notification
    metadata: {}
    data:
      message: The cat water is out!
      title: I'm thirsty..
  mode: single
- id: '1705556236317'
  alias: Turn off TV LED
  description: ''
  trigger:
  - platform: device
    type: changed_states
    device_id: 432719e49be7a5bcaa5b8c31996f40ea
    entity_id: 72204f9fff5ba7b0863083ab68b162d4
    domain: media_player
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition: []
  action:
  - type: turn_off
    device_id: d15b188afbaf9ee89d930c8562b90e43
    entity_id: 2b8e3356b2c40c937a32e0591a002acc
    domain: light
  mode: single
