- id: '1703910468139'
  alias: Dim lights when TV LED on
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: d15b188afbaf9ee89d930c8562b90e43
    entity_id: 2b8e3356b2c40c937a32e0591a002acc
    domain: light
  condition: []
  action:
  - device_id: 638ff6dbd16db764b99b0b1bc72a8a31
    domain: light
    entity_id: a37b21ddc27f77fa2c928543f0a7664a
    type: brightness_decrease
  mode: single
- id: '1704853898234'
  alias: Cat water fountain low
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: 249f4195abe2c4e17b946d59cda4a8c0
    entity_id: 5309c742c4d5a7d09930feb84d4bd64b
    domain: sensor
    below: 30
  condition: []
  action:
  - service: shopping_list.add_item
    metadata: {}
    data:
      name: cat water filter
  mode: single
