- id: '1697214175948'
  alias: Daily backup Samba
  description: Backs up to the samba share
  trigger:
  - platform: time
    at: 03:00:00
  condition: []
  action:
  - service: hassio.backup_full
    data:
      compressed: true
      location: Samba_Share
  mode: single
- id: '1703910468139'
  alias: Dim lights when TV LED on
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: d15b188afbaf9ee89d930c8562b90e43
    entity_id: 2b8e3356b2c40c937a32e0591a002acc
    domain: light
  condition: []
  action:
  - type: turn_off
    device_id: 638ff6dbd16db764b99b0b1bc72a8a31
    entity_id: a37b21ddc27f77fa2c928543f0a7664a
    domain: light
  mode: single
