#####
# This is all that remains of Configuration.yaml file.
# By using packages: I'm pulling all other configuration files
# from individual folders, starting with Integrations
#####

homeassistant:
  packages: !include_dir_named integrations     # package setup/config split
  
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

ecovacs:
  username: !secret default_email
  password: !secret ecovacs_password
  country: us
  continent: na