#####
# Update ping sensors on custom intervals
# https://github.com/home-assistant/core/issues/105041
#####

alias: Update ping sensors
id: d4a1dd58-5fed-4620-a2d1-50320ad0483e

description: 'Update different ping sensors at various intervals'

trigger:
  - trigger: time_pattern
    minutes: '/2'
    id: 'fast_ping'
  - trigger: time_pattern
    minutes: '/5'
    id: 'medium_ping'
  - trigger: time_pattern
    minutes: '/10'
    id: 'slow_ping'

action:
  - choose:
      - conditions:
          - condition: trigger
            id: 'fast_ping'
        sequence:
          - action: homeassistant.update_entity
            target:
              entity_id:
                - binary_sensor.poat_hole_local
                - binary_sensor.poat_seedbox_local

      - conditions:
          - condition: trigger
            id: 'medium_ping'
        sequence:
          - action: homeassistant.update_entity
            target:
              entity_id: binary_sensor.poat_share_local

      - conditions:
          - condition: trigger
            id: 'slow_ping'
        sequence:
          - action: homeassistant.update_entity
            target:
              entity_id: binary_sensor.poat_plex_local

mode: parallel
