#####
# Alerts if a smoke sensor is triggered
#####

alias: Smoke Sensor triggered
id: 525a78d5-ccf6-4154-893d-e7db44fdfb15

trigger:
- platform: state
  entity_id: group.smoke_sensors
  to: "on"

action:
  - service: notify.persistent_notification
    data:
      message: 'Smoke/CO sensor triggered!'
      title: '🔥 Smoke/CO sensor triggered!'
  - service: notify.mobile_app_poat_s_iphone_14_pro_max
    data:
      message: 'Smoke/CO sensor triggered!'
      title: '🔥 Smoke/CO sensor triggered!'
  - service: notify.mobile_app_gina_s_iphone_13_mini
    data:
      message: 'Smoke/CO sensor triggered!'
      title: '🔥 Smoke/CO sensor triggered!'
