#####
# Alerts if a smoke sensor is triggered
#####

alias: Smoke Sensor triggered
id: 525a78d5-ccf6-4154-893d-e7db44fdfb15

trigger:
- platform: state
  entity_id: group.smoke_sensors
  to: "on"

action:
  - service: script.notify_family
    data:
      message: 'Smoke/CO sensor triggered!'
      title: '🔥 Smoke/CO sensor triggered!'
      tag: smoke_sensor
