#####
# Notify when washing machine is done
#####

alias: Washy completed
id: 16b94df4-083a-45d4-9895-06dfa94c8a00

trigger:
  trigger: state
  entity_id: sensor.washy_running
  from: 'True'
  to: 'False'

action:
  action: notify.family_ai
  data:
    title: Washy done
    message: false
    data:
      prompt: washing machine is done
      backup: Washy has finished!
      tag: washy
