#####
# Updates the current theme based on triggers
#
#####

alias: Change Scenes
id: 16dd549f-4061-4bf2-b37d-6157bdfa0715

trigger:
  - platform: state
    alias: "People away"
    entity_id: zone.home
    to: "0"
    id: away

  - platform: state
    alias: "People home"
    entity_id: zone.home
    from: "0"
    id: home

  - platform: state
    entity_id:
      - input_boolean.on_vacation
    from: "on"
    to: "off"
    id: home

  - platform: state
    entity_id:
      - input_boolean.on_vacation
    from: "off"
    to: "on"
    id: vacation

  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: -4.0
    id: night

  - platform: sun
    event: sunrise
    id: morning

  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: -2.5
    id: evening

action:
  - choose:
      #####
      # Morning scene
      #  - open covers to desired position
      #####
      - conditions:
          condition: trigger
          id: morning
        sequence:
          service: scene.turn_on
          target:
            entity_id: scene.morning

      #####
      # Evening scene
      #  - close covers to desired position
      #####
      - conditions:
          condition: trigger
          id: evening
        sequence:
          service: scene.turn_on
          target:
            entity_id: scene.evening

      #####
      # Home scene
      #  - turns on some plugs and turns off eco
      #####
      - conditions:
          condition: trigger
          id: home
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.on_vacation
          - service: scene.turn_on
            target:
              entity_id: scene.home

      # away scene
      - conditions:
          condition: trigger
          id: away
        sequence:
          service: scene.turn_on
          target:
            entity_id: scene.away

      #####
      # Vacation scene
      #  - turn off some plugs and set to eco
      #####
      - conditions:
          condition: trigger
          id: vacation
        sequence:
          service: scene.turn_on
          target:
            entity_id: scene.vacation

      #####
      # Night scene
      #  - set AC to 71
      #####
      - conditions:
          condition: trigger
          id: night
        sequence:
          service: scene.turn_on
          target:
            entity_id: scene.night
  
  # reactivate vaca scene?
  - condition: state
    entity_id: input_boolean.on_vacation
    state: "on"
  - delay: 00:00:05
  - action: scene.turn_on
    target:
      entity_id: scene.vacation