#####
# TV turns on sound bar and LED
#####

alias: Turn on soundbar and TV LED when TV turned on
id: 9b349dfa-9719-4c2e-aeb7-e35de9e4618a

trigger:
  - platform: state
    entity_id:
      - media_player.living_room_fire_tv
    from: "off"
    to: idle

action:
  - parallel:
      - service: script.sound_bar_power
      - service: remote.send_command
        target:
          device_id: 7c0228accadb951d83724a364de2d662
        data:
          device: Living Room TV
          command: Mute
      - if:
          - condition: sun
            after: sunset
        then:
          - service: light.turn_on
            entity_id: light.tv_led
          - service: light.turn_off
            entity_id: light.living_room_light
