#####
# TV turns on sound bar and LED
#####

alias: Turn on soundbar and TV LED when TV turned on
id: 9b349dfa-9719-4c2e-aeb7-e35de9e4618a

trigger:
  - platform: state
    entity_id:
      - media_player.living_room_fire_tv
    from: "off"
    to: idle

action:
  - parallel:
      - service: script.sound_bar_power
      - service: remote.send_command
        target:
          device_id: 7c0228accadb951d83724a364de2d662
        data:
          device: Living Room TV
          command: Mute
      - if:
          - condition: sun
            after: sunset
        then:
          - type: turn_on
            device_id: d15b188afbaf9ee89d930c8562b90e43
            entity_id: 2b8e3356b2c40c937a32e0591a002acc
            domain: light
          - type: turn_off
            device_id: 638ff6dbd16db764b99b0b1bc72a8a31
            entity_id: a37b21ddc27f77fa2c928543f0a7664a
            domain: light
