#####
# Alerts if a vacuum has a problem
#####

alias: Vacuum issue
id: 7b40e36c-852c-4d34-acb9-f55c9530f496

trigger:
- platform: state
  entity_id: group.robot_vacuums_status
  to: "on"

condition:
  - condition: template
    value_template: '{{ not is_state_attr("vacuum.rolo", "status", "Dust bin missing")  }}'

action:
  - service: script.notify_family
    data:
      message: >
        Vacuum has an issue!
        
        
        Rolo:       {{ state_attr("vacuum.rolo", "status") }}
        
        Strong Boi: {{ state_attr("vacuum.e0000693817603917196", "error") }}
      title: '🤖 Vacuum problem!'
      tag: vacuum_issue
