#####
# Xbox turns TV on/off
#####

alias: Turn TV on/off when Xbox turned on/off
id: e85e41ea-5ff3-42ae-b5f3-5b6c0cfcccf6

trigger:
  - trigger: state
    entity_id: media_player.xbox_x
    from: "on"
    to: "off"
    id: xbox-off

  - trigger: state
    entity_id: media_player.xbox_x
    from: "off"
    to: "on"
    id: xbox-on

action:
  choose:
    - conditions:
        condition: trigger
        id: xbox-on
      sequence:
        action: media_player.turn_on
        target:
          entity_id: media_player.office_fire_tv
    - conditions:
        condition: trigger
        id: xbox-off
      sequence:
        action: media_player.turn_off
        target:
          entity_id: media_player.office_fire_tv
