#####
# Reset Cat Thirst filter when NFC tag scanned
#####

alias: Tag Cat Thirst is scanned
id: 39b6ff5c-3dcd-40e6-aca0-95a03fa42ed7
mode: single

trigger:
  trigger: tag
  tag_id: 0161dde0-0b79-4fea-b17d-3fa04096225b

action:
  # can't reset filter w/ current petkit integration
  - action: counter.decrement
    target:
      entity_id: counter.cat_filters
  - condition: numeric_state
    entity_id: counter.cat_filters
    below: 1
  - action: shopping_list.add_item
    data:
      name: cat water filters
