reboot_deco:
  name: Reboot Deco
  description: Reboot Deco
  fields:
    device_id:
      name: Device ID(s)
      description: Device ID(s)
      required: true
      selector:
        device:
          integration: tplink_deco
          manufacturer: TP-Link Deco
          multiple: true
