#####
# Alert when seedbox VPN is not running
#####

alias: Seedbox VPN off alert
id: 4cf2336b-949f-4241-adf7-2da850ab74ac

trigger:
  trigger: state
  entity_id: sensor.seedbox_vpn_on
  to: 'False'
  for:
    minutes: 1

action:
  - action: notify.persistent_notification
    data:
      message: 'VPN is not running on the seedbox.'
      title: '🔐 VPN Seedbox Alert!'
  - action: notify.mobile_app_poat_s_iphone_14_pro_max
    data:
      message: 'VPN is not running on the seedbox.'
      title: '🔐 VPN Seedbox Alert!'
