#####
# Alerts if a cat device has a problem
#####

alias: Cat device issue
id: 715a4f55-7a66-478a-b8ca-93cb1be8ff29

trigger:
- platform: state
  entity_id: group.cat_device_status
  to: "on"

action:
  - service: notify.persistent_notification
    data:
      message: 'Cat device has an issue!'
      title: '🐱 Cat device problem!'
  - service: notify.mobile_app_poat_s_iphone_14_pro_max
    data:
      message: 'Cat device has an issue!'
      title: '🐱 Cat device problem!'
