#####
# Alerts if a cat device has a problem
#####

alias: Cat device issue
id: 715a4f55-7a66-478a-b8ca-93cb1be8ff29

trigger:
  - platform: state
    entity_id: group.cat_device_status
    to: "on"
    for: "00:05:00"

action:
  - service: script.notify_family
    data:
      message: >
        Cat device has an issue!


        Water Level:          {{ states("binary_sensor.pet_thirst_water_level") }}

        Water Filter:         {{ states("binary_sensor.cat_filter_problem") }}


        Marbles Food Level:   {{ states("binary_sensor.cat_noms_food_level") }}

        Marbles Food Battery: {{ states("binary_sensor.cat_battery_problem") }}

        Marbles Desicant:     {{ states("binary_sensor.cat_desicant_problem") }}

        Marbles Food Status:  {{ states("binary_sensor.cat_noms_status_problem") }}
      title: "🐱 Cat device problem!"
      tag: cat_issue
