#####
# Notify when Dishwasher start
#####

alias: Dishwasher start
id: 7ed00e9c-edaf-42a0-b478-464142669ceb

trigger:
  trigger: numeric_state
  entity_id: sensor.dishwasher_7_1min
  above: 5
  for:
    minutes: 2

condition:
  condition: state
  entity_id: input_boolean.dishwasher_on
  state: 'off'

action:
- action: input_boolean.turn_on
  entity_id: input_boolean.dishwasher_on