#####
# Notify when Dishwasher is done
#####

alias: Dishwasher done
id: ff140942-ede2-46cf-a08d-7a44cb3ae6bf

trigger:
  platform: numeric_state
  entity_id: sensor.dishwasher_7_1min
  below: 2
  for: '00:05:00'

condition:
  condition: state
  entity_id: input_boolean.dishwasher_on
  state: "on"

action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.dishwasher_on

  - service: notify.family
    data:
      message: Empty me my overlord
      title: Dishwasher done!
