#####
# Notify when Dishwasher is done
#####

alias: Dishwasher done
id: ff140942-ede2-46cf-a08d-7a44cb3ae6bf

trigger:
  trigger: numeric_state
  entity_id: sensor.dishwasher_7_1min
  below: 2
  for:
    minutes: 5

condition:
  condition: state
  entity_id: input_boolean.dishwasher_on
  state: 'on'

action:
  - action: input_boolean.turn_off
    entity_id: input_boolean.dishwasher_on

  - action: notify.family_ai
    data:
      title: Dishwasher done!
      message: false
      data:
        prompt: dishwasher is done
        backup: The dishwasher is complete!
        tag: dishwasher_done
