#####
# Notify when Dryer is done
#####

alias: Dryer done
id: 7cc7b31e-f474-4db1-8765-052a9cccaf93

trigger:
  platform: numeric_state
  entity_id: sensor.dryer_1_1min
  below: 500
  for: '00:05:00'

condition:
  condition: state
  entity_id: input_boolean.dryer_on
  state: 'on'

action:
- service: input_boolean.turn_off
  entity_id: input_boolean.dryer_on

- service: notify.family
  data:
    message: Empty me and the lint thingy!
    title: Dryer done!