#####
# Set input boolean based on load sensor
#
#####

alias: Washer & Dryer
id: 00375bc8-c223-4914-a3d1-981a92fb915c

trigger:
  - trigger: numeric_state
    entity_id: sensor.clothes_washer_13_1min
    id: washer_on
    above: 20
    for: "00:00:10"
    variables:
      input_entity: input_boolean.washing_machine_on
      end_entity: input_boolean.washing_machine_end

  - trigger: numeric_state
    entity_id: sensor.clothes_washer_13_1min
    below: 2
    for: "00:20:00" # handle pause in soak
    id: washer_off
    variables:
      input_entity: input_boolean.washing_machine_on
      end_entity: input_boolean.washing_machine_end

  - trigger: numeric_state
    entity_id: sensor.dryer_1_1min
    above: 500
    for: "00:00:10"
    id: dryer_on
    variables:
      input_entity: input_boolean.dryer_on
      end_entity: input_boolean.dryer_end

  - trigger: numeric_state
    entity_id: sensor.dryer_1_1min
    below: 5
    for: "00:00:10"
    id: dryer_off
    variables:
      input_entity: input_boolean.dryer_on
      end_entity: input_boolean.dryer_end

  - trigger: device
    type: opened
    device_id: 357bc954ebb6225a55ae7d8b81f1fca7
    entity_id: 4986450410536f6afbeaefa26a3fd5ce
    domain: binary_sensor
    id: dryer_door
    variables:
      end_entity: input_boolean.dryer_end

action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - washer_on
              - dryer_on
          - condition: template
            value_template: '{{ states(input_entity)  == "off" }}'
        sequence:
          - action: input_boolean.turn_on
            target:
              entity_id: "{{ input_entity }}"
          - action: input_boolean.turn_off
            target:
              entity_id: "{{ end_entity }}"
          - condition: trigger
            id:
              - dryer_on
          - action: input_boolean.turn_off
            target:
              entity_id: input_boolean.washing_machine_end

      - conditions:
          - condition: trigger
            id:
              - washer_off
              - dryer_off
          - condition: template
            value_template: '{{ states(input_entity)  == "on" }}'
        sequence:
          - action: input_boolean.turn_off
            target:
              entity_id: "{{ input_entity }}"
          - action: input_boolean.turn_on
            target:
              entity_id: "{{ end_entity }}"

      - conditions:
          - condition: trigger
            id:
              - dryer_door
        sequence:
          - action: input_boolean.turn_off
            target:
              entity_id: "{{ end_entity }}"
