#####
# Set input boolean based on load sensor
#####

alias: Washing Machine
id: 00375bc8-c223-4914-a3d1-981a92fb915c

trigger:
  - platform: numeric_state
    entity_id: sensor.clothes_washer_13_1min
    id: turned_on
    above: 20
    for: '00:00:10'
  - platform: numeric_state
    entity_id: sensor.clothes_washer_13_1min
    below: 2
    for: "00:20:00" # handle pause in soak
    id: turned_off

action:
  - choose:
    - conditions:
      - condition: trigger
        id: turned_on
      - condition: state
        entity_id: input_boolean.washing_machine_on
        state: 'off'
      sequence:
        - service: input_boolean.turn_on
          entity_id: input_boolean.washing_machine_on
    - conditions:
      - condition: trigger
        id: turned_off
      - condition: state
        entity_id: input_boolean.washing_machine_on
        state: "on"
      sequence:
        - service: input_boolean.turn_off
          entity_id: input_boolean.washing_machine_on
