#####
# Set input boolean based on load sensor
#
#####

alias: Washer & Dryer
id: 00375bc8-c223-4914-a3d1-981a92fb915c

trigger:
  - platform: numeric_state
    entity_id: sensor.clothes_washer_13_1min
    id: washer_on
    above: 20
    for: "00:00:10"

  - platform: numeric_state
    entity_id: sensor.clothes_washer_13_1min
    below: 2
    for: "00:20:00" # handle pause in soak
    id: washer_off

  - platform: state
    entity_id:
      - binary_sensor.dryer_on
    from: "off"
    to: "on"
    id: dryer_on

  - platform: device
    type: opened
    device_id: 357bc954ebb6225a55ae7d8b81f1fca7
    entity_id: 4986450410536f6afbeaefa26a3fd5ce
    domain: binary_sensor
    id: dryer_door

action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - washer_on
          - condition: template
            value_template: '{{ states("input_boolean.washing_machine_on")  == "off" }}'
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.washing_machine_on

      - conditions:
          - condition: trigger
            id:
              - washer_off
          - condition: template
            value_template: '{{ states("input_boolean.washing_machine_on")  == "on" }}'
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.washing_machine_on

      - conditions:
          - condition: trigger
            id:
              - dryer_on
        sequence:
          - service: alert.turn_off
            target:
              entity_id: alert.washing_machine

      - conditions:
          - condition: trigger
            id:
              - dryer_door
        sequence:
          - service: alert.turn_off
            target:
              entity_id: alert.dryer
