#####
# Notify when Washing Machine is done
#####

alias: Washing Machine done
id: 832e3b5b-c7cf-4216-b737-dcc9a66ee5dc

trigger:
  platform: numeric_state
  entity_id: sensor.clothes_washer_13_1min
  below: 2
  for: '00:00:10'

condition:
  condition: state
  entity_id: input_boolean.washing_machine_on
  state: 'on'

action:
- service: input_boolean.turn_off
  data: {}
  entity_id: input_boolean.washing_machine_on

- service: notify.persistent_notification
  metadata: {}
  data:
    message: Time to load the dryer...
    title: Washer done!