#####
# Alert when water leak is detected
# Binary sensors changes from off
#####

alias: Water Leak Alert
id: edd5b0f3-c59b-4f09-862b-b6eb5b0c81d0
trigger:
  - platform: state
    entity_id: group.leak_sensors
    to: 'on'
action:
  - service: notify.persistent_notification
    data:
      message: 'Water leak detected - check sensors now!'
      title: '💧 Water Leak Alert!'
  - service: notify.mobile_app_poat_s_iphone_14_pro_max
    metadata: {}
    data:
      message: 'Water leak detected - check sensors now!'
      title: '💧 Water Leak Alert!'