#####
# TV turns off TV led and sound bar
#####

alias: Turn off TV LED when TV turned off
id: 16f855bf-9b9b-4028-93b8-17fd0c3dd6a2

trigger:
  platform: state
  entity_id:
    - media_player.living_room_fire_tv
  from:
    - playing
    - idle
    - pause
    - standby
  to: "off"

action:
  parallel:
    - service: script.sound_bar_power
    - service: light.turn_off
      target:
        entity_id: light.tv_led
