#####
# Triggers when there is new warning or error
# https://community.home-assistant.io/t/counter-warning-error-issue/85490/11
#####

alias: Count Home Assistant errors
id: 'c057ca2c-ab20-4fe0-a32b-5980c0990fb2'

trigger:
  # event_data.level cannot accept a list of values
  - trigger: event
    event_type: system_log_event
    event_data:
      level: ERROR
  - trigger: event
    event_type: system_log_event
    event_data:
      level: WARNING

action:
  - action: counter.increment
    target:
      entity_id: >
        counter.homeassistant_{{ trigger.event.data.level | lower }}s

mode: queued
max: 20
max_exceeded: silent
