name: Sync to Public Repository

on:
  push:
    branches:
      - home # Adjust this if you use a different default branch

jobs:
  sync-public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to public repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:warmfire540/home-assistant-config-public.git
          ssh_private_key: ${{ secrets.PUBLIC_REPO_SSH_PRIVATE_KEY }}
